# Generated by Django 3.2.19 on 2023-05-15 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_promo', '0004_auto_20211221_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliatenetwork',
            options={'ordering': ['-modified'], 'verbose_name_plural': 'Партнерские сети'},
        ),
        migrations.AlterModelOptions(
            name='downloadedpromo',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Скачанные промо'},
        ),
        migrations.AlterModelOptions(
            name='geo',
            options={'ordering': ['name'], 'verbose_name_plural': 'Гео'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['-modified'], 'verbose_name_plural': 'Конфиги'},
        ),
        migrations.AlterModelOptions(
            name='parserbatch',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Пакетные запросы'},
        ),
        migrations.AlterModelOptions(
            name='presetparser',
            options={'ordering': ['name'], 'verbose_name_plural': 'Пресеты парсера'},
        ),
    ]
